/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AlgoSequenceKelompok3;

import static AlgoSequenceKelompok3.KasirPengembalian.tabelmodel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static AlgoSequenceKelompok3.KasirPengembalian.jTablePengembalian;

/**
 *
 * @author naintu
 */
public class AdminTransaksi extends javax.swing.JPanel {

    /**
     * Creates new form AdminTransaksi
     */
    
    Connection con;
    PreparedStatement pst;
    PreparedStatement pst2;
    ResultSet rs;
    Statement stm;
    DefaultTableModel tabelmodel;
    
    public AdminTransaksi() {
        initComponents();
        
        String []tabelHeader = {"ID","Nama","Alamat","Tanggal Pinjam","Tanggal Pengembalian","Denda","Status"};
        tabelmodel = new DefaultTableModel(tabelHeader, 0);
        jTableTransaksi.setModel(tabelmodel);
        showTabel();
    }
    
    private void showTabel(){
        int row = jTableTransaksi.getRowCount();
        for(int i=0; i<row; i++){
            tabelmodel.removeRow(0);
        }
        try{
            con = Koneksi.getConnection();
            stm = con.createStatement();
            String SQL = ("select transaksi.id_transaksi, penyewa.nama, penyewa.alamat, transaksi.tanggal_pinjam, transaksi.tanggal_pengembalian, transaksi.denda, sewa.status from penyewa, barang, sewa, transaksi where penyewa.id_penyewa = sewa.id_penyewa and barang.kode_barang = sewa.kode_barang and transaksi.id_transaksi = sewa.id_transaksi");
            rs = stm.executeQuery(SQL);
            while(rs.next()){
                String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)};
                tabelmodel.addRow(data);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transaksiPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jcari = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTransaksi = new javax.swing.JTable();

        transaksiPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 165, 186));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Data Transaksi");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon search blue.png"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 17, 20, 20));

        jcari.setBackground(new java.awt.Color(0, 165, 186));
        jcari.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jcari.setForeground(new java.awt.Color(255, 255, 255));
        jcari.setBorder(null);
        jcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcariKeyReleased(evt);
            }
        });
        jPanel4.add(jcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 12, 250, 25));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 37, 250, 1));

        transaksiPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1026, 60));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableTransaksi.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "Tanggal", "Denda", "Total", "Pembayaran", "Kembalian"
            }
        ));
        jTableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableTransaksi);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 986, 558));

        transaksiPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1026, 598));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(transaksiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTransaksiMouseClicked
        // TODO add your handling code here:
        int i = jTableTransaksi.getSelectedRow();
        AdminBon bonklik = new AdminBon(jTableTransaksi.getValueAt(i, 0).toString());
        bonklik.setVisible(true);
    }//GEN-LAST:event_jTableTransaksiMouseClicked

    private void jcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcariKeyReleased
        // TODO add your handling code here:
        String cari = jcari.getText().trim();
        while(jTableTransaksi.getRowCount() > 0){
            tabelmodel.removeRow(0);
        }
        try{
            con = Koneksi.getConnection();
            stm = con.createStatement();
            rs = stm.executeQuery("select transaksi.id_transaksi, penyewa.nama, penyewa.alamat, transaksi.tanggal_pinjam, transaksi.tanggal_pengembalian, transaksi.denda, sewa.status from penyewa, barang, sewa, transaksi where penyewa.id_penyewa = sewa.id_penyewa and barang.kode_barang = sewa.kode_barang and transaksi.id_transaksi = sewa.id_transaksi and penyewa.nama like '%"+cari+"%'");
            if(rs.first()){
                String data[] = new String[7];
                do{
                    for(int i=0;i<7;i++){
                        data[i] = rs.getString(i+1);
                    }
                    tabelmodel.addRow(data);
                }
                while(rs.next());
            }
            rs.close();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jcariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTransaksi;
    private javax.swing.JTextField jcari;
    private javax.swing.JPanel transaksiPanel;
    // End of variables declaration//GEN-END:variables
}
