/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AlgoSequenceKelompok3;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author naintu
 */
public class KasirBon extends javax.swing.JFrame {

    /**
     * Creates new form KasirBon
     */
    
    Connection con;
    PreparedStatement pst;
    PreparedStatement pst2;
    PreparedStatement pst3;
    PreparedStatement pst4;
    ResultSet rs;
    ResultSet rs2;
    ResultSet rs3;
    Statement stm;
    Statement stm2;
    DefaultTableModel tabelmodel;
    
    public KasirBon() {
        initComponents();
        
        String []tabelHeader = {"Kode Barang","Nama Barang","Jenis Barang","Harga Sewa","Jumlah","Total"};
        tabelmodel = new DefaultTableModel(tabelHeader, 0);
        jTableStruk.setModel(tabelmodel);
        showTabel();
    }
    
    private void showTabel(){
        int row = jTableStruk.getRowCount();
        for(int i=0; i<row; i++){
            tabelmodel.removeRow(0);
        }
        try{
            con = Koneksi.getConnection();
            stm = con.createStatement();
            String SQL = ("select penyewa.nama, penyewa.alamat, barang.kode_barang, barang.nama_barang, barang.jenis_barang, barang.harga_sewa, sewa.qty, sewa.total, transaksi.tanggal_pinjam, transaksi.tanggal_pengembalian, transaksi.diskon, transaksi.total_transaksi, transaksi.pembayaran from penyewa, barang, sewa, transaksi where penyewa.id_penyewa = sewa.id_penyewa and barang.kode_barang = sewa.kode_barang and transaksi.id_transaksi = sewa.id_transaksi order by transaksi.id_transaksi desc limit 1");
            rs = stm.executeQuery(SQL);
            int total_transaksi = 0;
            int pembayaran = 0;
            while(rs.next()){
                String data[] = {rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                tabelmodel.addRow(data);
                jLabelNama.setText(rs.getString("nama"));
                jLabelAlamat.setText(rs.getString("alamat"));
                jLabelTglPinjam.setText(rs.getString("tanggal_pinjam"));
                jLabelTglKembali.setText(rs.getString("tanggal_pengembalian"));
                jLabelDiskon.setText(rs.getString("diskon"));
                jLabelTotal.setText(rs.getString("total_transaksi"));
                total_transaksi = rs.getInt("total_transaksi");
                pembayaran = rs.getInt("pembayaran");
            }
            int kembalian = pembayaran-total_transaksi;
            jLabelKembalian.setText(Integer.toString(kembalian));
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notifikasiPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStruk = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelDiskon = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelTglPinjam = new javax.swing.JLabel();
        jLabelTglKembali = new javax.swing.JLabel();
        jLabelKembalian = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelAlamat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        notifikasiPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(71, 68, 67));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1002, 3, 20, 15));

        notifikasiPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1026, 20));

        jPanel4.setBackground(new java.awt.Color(122, 171, 65));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Struk");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, -1, -1));

        notifikasiPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1026, 60));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableStruk.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTableStruk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Jenis Barang", "Harga Sewa", "Jumlah", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTableStruk);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 986, 200));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button cetak.png"))); // NOI18N
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 100, 30));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel1.setText("Diskon           : Rp.");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setText("Total              : Rp.");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, -1, -1));

        jLabelDiskon.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelDiskon.setText("0");
        jPanel5.add(jLabelDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, -1, -1));

        jLabelTotal.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelTotal.setText("0");
        jPanel5.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel3.setText("Kembalian    : Rp.");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel4.setText("Tanggal Pinjam               :");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel5.setText("Tanggal Pengembalian :");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabelTglPinjam.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelTglPinjam.setText("2018/08/12");
        jPanel5.add(jLabelTglPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jLabelTglKembali.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelTglKembali.setText("2018/08/15");
        jPanel5.add(jLabelTglKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        jLabelKembalian.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelKembalian.setText("0");
        jPanel5.add(jLabelKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel6.setText("Nama   :");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelNama.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelNama.setText("Odang");
        jPanel5.add(jLabelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel7.setText("Alamat :");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabelAlamat.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabelAlamat.setText("Bandung");
        jPanel5.add(jLabelAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        notifikasiPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1026, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(notifikasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1026, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notifikasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        new StrukFrame().setVisible(true);
        try{
            String NamaFile = "./src/AlgoSequenceKelompok3/NewStrukReport.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/sewa","root","");
            HashMap param = new HashMap();
            //Mengambil parameter
            con = Koneksi.getConnection();
            stm = con.createStatement();
            String SQL = "select id_transaksi from transaksi order by id_transaksi desc limit 1";
            rs = stm.executeQuery(SQL);
            String id_transaksi = null;
            while(rs.next()){
                id_transaksi = rs.getString("id_transaksi");
            }
            param.put("id_transaksi",id_transaksi);
            
            File reportFile = new File (NamaFile);
                   
            JasperReport jReport = (JasperReport) JRLoader.loadObject(reportFile.getPath());
            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JRViewer viewReport = new JRViewer(JPrint);
            viewReport.setOpaque(true);
            viewReport.setVisible(true);
            StrukFrame.jFrameReport.add(viewReport);
            StrukFrame.jFrameReport.setViewportView(viewReport);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Kesalahan mencetak struk");
            System.err.println("Kesalahan mencetak struk");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirBon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirBon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirBon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirBon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasirBon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAlamat;
    private javax.swing.JLabel jLabelDiskon;
    private javax.swing.JLabel jLabelKembalian;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelTglKembali;
    private javax.swing.JLabel jLabelTglPinjam;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStruk;
    private javax.swing.JPanel notifikasiPanel;
    // End of variables declaration//GEN-END:variables
}
