/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AlgoSequenceKelompok3;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author naintu
 */
public class KasirPengembalian extends javax.swing.JPanel {

    /**
     * Creates new form KasirPengembalian
     */
    
    Connection con;
    PreparedStatement pst;
    PreparedStatement pst2;
    ResultSet rs;
    Statement stm;
    static DefaultTableModel tabelmodel;
    
    public KasirPengembalian() {
        initComponents();
        
        String []tabelHeader = {"ID","Nama","Alamat","Tanggal Pinjam","Tanggal Pengembalian","Denda","Status"};
        tabelmodel = new DefaultTableModel(tabelHeader, 0);
        jTablePengembalian.setModel(tabelmodel);
        showTabel();
    }
    
    public void showTabel(){
        int row = jTablePengembalian.getRowCount();
        for(int i=0; i<row; i++){
            tabelmodel.removeRow(0);
        }
        try{
            con = Koneksi.getConnection();
            stm = con.createStatement();
            String SQL = ("select transaksi.id_transaksi, penyewa.nama, penyewa.alamat, transaksi.tanggal_pinjam, transaksi.tanggal_pengembalian, transaksi.denda, sewa.status from penyewa, barang, sewa, transaksi where penyewa.id_penyewa = sewa.id_penyewa and barang.kode_barang = sewa.kode_barang and sewa.status = 'disewa' and transaksi.id_transaksi = sewa.id_transaksi");
            rs = stm.executeQuery(SQL);
            while(rs.next()){
                String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)};
                tabelmodel.addRow(data);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        penyewaanPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jcari = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePengembalian = new javax.swing.JTable();

        penyewaanPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 165, 186));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Data Penyewaan");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon search blue.png"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 17, 20, 20));

        jcari.setBackground(new java.awt.Color(0, 165, 186));
        jcari.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jcari.setForeground(new java.awt.Color(255, 255, 255));
        jcari.setBorder(null);
        jcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcariKeyReleased(evt);
            }
        });
        jPanel4.add(jcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 12, 250, 25));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 37, 250, 1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button refresh.png"))); // NOI18N
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 15, 60, 30));

        penyewaanPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1026, 60));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePengembalian.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTablePengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "Tanggal Pinjam", "Tanggal Pengembalian", "Denda", "Status"
            }
        ));
        jTablePengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePengembalianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTablePengembalianMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePengembalian);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 986, 558));

        penyewaanPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1026, 598));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(penyewaanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(penyewaanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePengembalianMouseClicked
        // TODO add your handling code here:
        int i = jTablePengembalian.getSelectedRow();
        BonClik bonklik = new BonClik(jTablePengembalian.getValueAt(i, 0).toString());
        bonklik.setVisible(true);
    }//GEN-LAST:event_jTablePengembalianMouseClicked

    private void jcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcariKeyReleased
        // TODO add your handling code here:
//        String cari = jcari.getText().trim();
//        while(jTablePengembalian.getRowCount() > 0){
//            tabelmodel.removeRow(0);
//        }
//        try{
//            con = Koneksi.getConnection();
//            stm = con.createStatement();
//            rs = stm.executeQuery("select transaksi.id_transaksi, penyewa.nama, penyewa.alamat, transaksi.tanggal_pinjam, transaksi.tanggal_pengembalian, transaksi.denda, sewa.status from penyewa, barang, sewa, transaksi where penyewa.id_penyewa = sewa.id_penyewa and barang.kode_barang = sewa.kode_barang and transaksi.id_transaksi = sewa.id_transaksi and sewa.status = 'disewa' and penyewa.nama like '%"+cari+"%'");
//            if(rs.first()){
//                String data[] = new String[7];
//                do{
//                    for(int i=0;i<7;i++){
//                        data[i] = rs.getString(i+1);
//                    }
//                    tabelmodel.addRow(data);
//                }
//                while(rs.next());
//            }
//            rs.close();
//        }
//        catch(Exception ex){
//            JOptionPane.showMessageDialog(null, ex.getMessage());
//        }
    }//GEN-LAST:event_jcariKeyReleased

    private void jTablePengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePengembalianMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablePengembalianMouseEntered

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        showTabel();
    }//GEN-LAST:event_jButton10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTablePengembalian;
    private javax.swing.JTextField jcari;
    private javax.swing.JPanel penyewaanPanel;
    // End of variables declaration//GEN-END:variables
}
